---
dist: xenial
sudo: true
language: python

python:
- 3.6
- 3.7

install:
- pip install tox-travis
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    sudo apt-get install libsdl-ttf2.0-0
  ; fi
script:
- tox

stages:
- lint
- test
- publish

jobs:
  allow_failures:
  - python: 3.7
  - { os: osx, stage: publish }

  include:
  - { stage: lint, python: 3.6, env: TOXENV=flake8 }
  - { stage: lint, python: 3.6, env: TOXENV=pylint }
  - { stage: test, os: osx, language: generic, env: TOXENV=py36 }

  - name: PyPI package
    stage: publish
    python: 3.6
    install: skip
    script: skip
    deploy:
      provider: pypi
      user: coolRR
      password:
        secure: lQ78pXBQXq2hgrgtlgLak15RVzMGpDJP8ncbenJgpdT0EmTc98MRvQeFsNgiwTKLvkyNZzFs1tG2LjdWX5i7DRwxoAXYObzMiexOfTd6tjQt1/KwuZDWpmMqpBmNGRxzpHbX/0gFWlZ6dY5/y5Wh9FSvXfwYzK1dkscgtdOayB3hHR6y/wOodiZa44k49q+dGKGlJnvbaDK6ngescWX+MIwV3LpiWlooB/S6sPbRg991sfuNc+tbO5LVHvlmDy6oECLqZ6uBLHKrSOZMeKULnJKWHFfUBkeb/ajzrP2O3KYD8rvMaeR9a99iQWRcIs97jLNHtcVx1OR79b49A1HnjjuxYdmksSn7sTF0YbugJJbEq0kQLtoNfOY5C+FnSfj8z2CLLAEOKUHgX/JDHoJmwVpnrY1CVLRIR3zR60RchwGO6Y7WqqjQGbpVJN1H+1kY66EXec28kycalbLVprea9YyMkvVNgu4wwiFu5O+2Td3bptqQstSmUZb+fHt334EISFcA3OEn0JEToNPP3ZjmtwJCTNEt+DViZ5gtatsxptGZr5NzJx3BENPyO3jktga1hw9nmY/pjH9Efu8TRdqzGM7WJMgeO6bBlCncwBQHz60r4AOuTFreZ3Cz7DoVDGKBYOk4oOUvbvv1BINAcRhPijSzhh46atakspBKBk0iEn4=
      distributions: 'sdist bdist_wheel'
      skip_cleanup: true
      on:
        tags: true

  - name: GNU/Linux AppImage
    stage: publish
    python: 3.6
    install:
    - sudo apt-get install desktop-file-utils
    - wget https://raw.githubusercontent.com/AppImage/AppImages/master/pkg2appimage
    - chmod 755 pkg2appimage
    script:
    - ./pkg2appimage AppImage.yml
    - bash -c "mv -v out/Python*AppImage PythonTurtle.AppImage"
    deploy:
      provider: releases
      api_key: EY5m706JrxnEaSK7s3knGQj4cO8rHQyIztRq4UhN+zx0xCGuq65rBOPB7/dtthLgpB9cjWHbN3RQZOi9OiPlzaimMaZT4q1rQo+0bMoH61ML/xSXG3xY6dhCdQXvNElDerii6K0tgWJtnOOylvnNv4YWw+IlUMHXHCpwg0ZcDu2yLmpyozqAzSiMIbPa2UQtG0idFKyh59EwAdEohOC9WuqGLdF7ngJCEcF/C0+DHgH1MJsblmognrng2RAjhzbQNjQD5YLLQ7h4ODYGPRqr1aw1TXObmRH6AOVMpGSTFbFwOgTJoYZp2NKDL6ffjxR0YAxkgXLcv1c/xsp1qe3RAYflLGAz2Gw5cSRL1HhB8qtVrfFdXkBO7Gc9dtj+wOOmn9o/9OaaISvYcmXJv63x4oz8As1TXXO+Xf9zRhnxBKeDTlPsOSAzgWMPq2RKTwVjpWfslxqtEFrgYtjf0QArly+XahX244umLd2pFb4mLhmQyHFIhTb2pu+9f/nQkeBNogpB1PVPdLhrySvnR/6kdjsDyMnNIY8ROs4c/ZHfwm3sPAztlbIYByZFR4cjzRGObsZBKbUG1R1w47FYk2uE055V73sktJYsxAe+HBFfN85VSLOi8nLU160MLEWNhzMbGm0rnqLnmVx6Q7Va35KdbrgnXnHyhwUUUUQWNvI7ZTo=
      file: PythonTurtle.AppImage
      skip_cleanup: true
      on:
        tags: true

  - name: GNU/Linux bundle
    stage: publish
    python: 3.6
    install:
    - pip install PyInstaller
    - pip install --find-links https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04 wxPython
    script:
    - ./setup.py clean bundle
    deploy:
      provider: releases
      api_key: $GITHUB_TOKEN
      file: dist/PythonTurtle
      skip_cleanup: true
      on:
        tags: true

  - name: macOS bundle
    stage: publish
    os: osx
    language: generic
    install:
    - python3 --version
    - python3 -m pip install --upgrade pip
    - python3 -m pip install PyInstaller wxPython
    script:
    - ./setup.py clean bundle
    deploy:
      provider: releases
      api_key: $GITHUB_TOKEN
      file: dist/PythonTurtle
      skip_cleanup: true
      on:
        tags: true
