---
dist: xenial
sudo: true

language: python
python:
  - 3.6
  - 3.7
  - pypy3

stages:
  - lint
  - test
  - build

env:  # enable allow_failures
matrix:
  allow_failures:
    - env: TOXENV=pylint
    - python: pypy3
    - python: 3.7

jobs:
  include:
    - { stage: lint, python: 3.6, env: TOXENV=flake8 }
    - { stage: lint, python: 3.6, env: TOXENV=pylint }

before_install:
  - sudo apt-get update
  - PYTHON_MAJOR=$(python -c 'import sys; print(sys.version[0])')
  # - if [ $PYTHON_MAJOR = '3' ]; then sudo apt-get install -y python3-wxgtk4.0; fi
  - dpkg -l *wxgtk*

install: pip install tox-travis
script: tox
