---
image:
- Visual Studio 2017
- Ubuntu

environment:
  matrix:
  - PYTHON: "C:\\Python36"

install:
- "%PYTHON%\\python.exe -m pip install PyInstaller wxPython"

build: off

build_script:
- "%PYTHON%\\python.exe setup.py clean bundle"

artifacts:
- path: dist

on_success:
- dir dist
